services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Subhan56%23
      POSTGRES_DB: habit_tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:Subhan56%23@db:5432/habit_tracker
      DB_PORT: 5000
    depends_on:
      - db

volumes:
  pgdata: